image: node:lts-bullseye
pages:
  stage: deploy
  cache:
    key:
      files:
        - bun.lockb
      prefix: bun
    paths:
      - node_modules/
  script:
    - apt-get update && apt-get install -y calibre --no-install-recommends
    - apt-get update && apt-get install -y fontconfig unzip
    - unzip "./fonts/*.zip" -d /usr/share/fonts/
      && fc-cache -fv
    - pnpm install
    - env LANG=ja_JP.UTF-8 pnpm run build
    - cp -a _book/. public/
  artifacts:
    paths:
      - public/
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
