image: node:lts-bullseye
pages:
  stage: deploy
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - node_modules/
  script:
    - apt-get update && apt-get install -y calibre --no-install-recommends
    - apt-get update && apt-get install -y fontconfig unzip sudo
    - unzip "./fonts/*.zip" -d /usr/share/fonts/
      && fc-cache -fv
    - sudo corepack enable
    - sudo -u node pnpm install
    - sudo -u node env LANG=ja_JP.UTF-8 pnpm run build
    - cp -a _book/ public/webbook/
  artifacts:
    paths:
      - public/
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
